export default [
  {
    url: `asset:/files/youareawesome.wav`, //`asset:/files/clickon.mp3`,
    title: 'youareawesome',
    artist: 'eFlashApps',
    artwork: `asset:/files/youareawesome.wav`,
    duration: 0,
  },
  {
    url: `asset:/files/spectacular.wav`, //`asset:/files/clickon.mp3`,
    title: 'spectacular',
    artist: 'eFlashApps',
    artwork: `asset:/files/spectacular.wav`,
    duration: 0,
  },
  {
    url: `asset:/files/sensational.wav`, //`asset:/files/clickon.mp3`,
    title: 'sensational',
    artist: 'eFlashApps',
    artwork: `asset:/files/sensational.wav`,
    duration: 0,
  },
  {
    url: `asset:/files/great.wav`, //`asset:/files/clickon.mp3`,
    title: 'great',
    artist: 'eFlashApps',
    artwork: `asset:/files/great.wav`,
    duration: 0,
  },
  {
    url: `asset:/files/goodjob.wav`, //`asset:/files/clickon.mp3`,
    title: 'goodjob',
    artist: 'eFlashApps',
    artwork: `asset:/files/goodjob.wav`,
    duration: 0,
  },
  {
    url: `asset:/files/goodanswer.wav`, //`asset:/files/clickon.mp3`,
    title: 'goodanswer',
    artist: 'eFlashApps',
    artwork: `asset:/files/goodanswer.wav`,
    duration: 0,
  },
  {
    url: `asset:/files/clapping.mp3`, //`asset:/files/clickon.mp3`,
    title: 'clapping',
    artist: 'eFlashApps',
    artwork: `asset:/files/clapping.mp3`,
    duration: 0,
  },
  {
    url: `asset:/files/bravo.wav`, //`asset:/files/clickon.mp3`,
    title: 'bravo',
    artist: 'eFlashApps',
    artwork: `asset:/files/bravo.wav`,
    duration: 0,
  },
  {
    url: `asset:/files/correct.wav`, //`asset:/files/clickon.mp3`,
    title: 'correct',
    artist: 'eFlashApps',
    artwork: `asset:/files/correct.wav`,
    duration: 0,
  },
];
