import { path } from "./path";
export default [
  {
    url: `${path}youareawesome.wav`, //`asset:/files/clickon.mp3`,
    title: 'youareawesome',
    artist: 'eFlashApps',
    artwork: `${path}youareawesome.wav`,
    duration: 0,
  },
  {
    url: `${path}spectacular.wav`, //`${path}clickon.mp3`,
    title: 'spectacular',
    artist: 'eFlashApps',
    artwork: `${path}spectacular.wav`,
    duration: 0,
  },
  {
    url: `${path}sensational.wav`, //`${path}clickon.mp3`,
    title: 'sensational',
    artist: 'eFlashApps',
    artwork: `${path}sensational.wav`,
    duration: 0,
  },
  {
    url: `${path}great.wav`, //`${path}clickon.mp3`,
    title: 'great',
    artist: 'eFlashApps',
    artwork: `${path}great.wav`,
    duration: 0,
  },
  {
    url: `${path}goodjob.wav`, //`asset:/files/clickon.mp3`,
    title: 'goodjob',
    artist: 'eFlashApps',
    artwork: `${path}goodjob.wav`,
    duration: 0,
  },
  {
    url: `${path}goodanswer.wav`, //`asset:/files/clickon.mp3`,
    title: 'goodanswer',
    artist: 'eFlashApps',
    artwork: `${path}goodanswer.wav`,
    duration: 0,
  },
  {
    url: `${path}clapping.mp3`, //`asset:/files/clickon.mp3`,
    title: 'clapping',
    artist: 'eFlashApps',
    artwork: `${path}clapping.mp3`,
    duration: 0,
  },
  {
    url: `${path}bravo.wav`, //`asset:/files/clickon.mp3`,
    title: 'bravo',
    artist: 'eFlashApps',
    artwork: `${path}bravo.wav`,
    duration: 0,
  },
  {
    url: `${path}correct.wav`, //`asset:/files/clickon.mp3`,
    title: 'correct',
    artist: 'eFlashApps',
    artwork: `${path}correct.wav`,
    duration: 0,
  },
];
